[package]
name = "const_soft_float"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[features]
no_std = []
const_trait_impl = []
const_mut_refs = []

[dependencies]

#[dependencies.compiler_builtins]
#version = "0.1.87"
