[package]
name = "fuzz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
const_soft_float = { path = ".." }
libm = "0.2.6"
nanorand = "0.7.0"
